apiVersion: v1
kind: Service
metadata:
  name: TO_DO-service
  labels:
    app: TO_DO
spec:
  type: NodePort
  selector:
    app: TO_DO
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
